### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by ryannealmes** [dcalacci/breakout#44]
When spinning up the server I get the following warning

```
(node) warning: possible EventEmitter memory leak detected. 2 connection listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Namespace.addListener (events.js:239:17)
    at /Users/ryanme/sites/work/breakout/server/node_modules/feathers-socket-commons/lib/index.js:44:22
    at Object.setup (/Users/ryanme/sites/work/breakout/server/node_modules/feathers-socket-commons/lib/index.js:47:11)
    at Object.setup (/Users/ryanme/sites/work/breakout/server/node_modules/uberproto/lib/proto.js:30:17)
    at EventEmitter.service (/Users/ryanme/sites/work/breakout/server/node_modules/feathers/lib/application.js:77:20)
    at EventEmitter.use (/Users/ryanme/sites/work/breakout/server/node_modules/feathers/lib/application.js:110:10)
    at EventEmitter.use (/Users/ryanme/sites/work/breakout/server/node_modules/uberproto/lib/proto.js:30:17)
    at /Users/ryanme/sites/work/breakout/server/app.js:60:9
    at /Users/ryanme/sites/work/breakout/server/node_modules/mongodb/lib/mongo_client.js:519:11
    at doNTCallback0 (node.js:428:9)
```

Any ideas?

**Comment by dcalacci** [comment]
Right now it seems to me like this is a problem in feathers and the mongodb adapter.

Doing some reading, it doesn't seem to be dangerous...

In any case, [I'm moving the codebase to mongoose](https://github.com/feathersjs/feathers-mongoose), and this error no longer appears on the `feature/db-schema` branch where I'm doing that work

_(ツ)_/¯
